<?php

namespace Ced\Cdiscount\Model\Config\Source;

class ShipmentMethods extends \Magento\Shipping\Model\Config\Source\Allmethods
{
    public function toOptionArray($isActiveOnlyFlag = true)
    {
        return parent::toOptionArray($isActiveOnlyFlag); // TODO: Change the autogenerated stub
    }
}